export const translations = {
  'pt-br': {
    comparisonEyebrow: 'Diferenciais',
    comparisonTitle: 'A mesma tarefa, sem a mesma dor de cabeça',
    comparisonColCriteria: 'Critério',
    comparisonColOthers: 'OpenShift / Rancher',
    comparisonColGreencap: 'GreenCap K8s',
    comparisonRow1Criteria: 'Setup inicial',
    comparisonRow1Others: 'Horas a dias',
    comparisonRow1Greencap: 'Minutos, um único container',
    comparisonRow2Criteria: 'Custo operacional',
    comparisonRow2Others: 'Alto',
    comparisonRow2Greencap: 'Mínimo',
    comparisonRow3Criteria: 'Curva de aprendizado',
    comparisonRow3Others: 'Alta',
    comparisonRow3Greencap: 'Baixa',
    comparisonRow4Criteria: 'Deploy de aplicação',
    comparisonRow4Others: 'Múltiplos passos manuais',
    comparisonRow4Greencap: '1 clique via Templates',
    comparisonRow5Criteria: 'Licença',
    comparisonRow5Others: 'Comercial / enterprise',
    comparisonRow5Greencap: 'Open source'
  },
  'en': {
    comparisonEyebrow: 'Differentiators',
    comparisonTitle: 'The same task, without the same headache',
    comparisonColCriteria: 'Criteria',
    comparisonColOthers: 'OpenShift / Rancher',
    comparisonColGreencap: 'GreenCap K8s',
    comparisonRow1Criteria: 'Initial setup',
    comparisonRow1Others: 'Hours to days',
    comparisonRow1Greencap: 'Minutes, a single container',
    comparisonRow2Criteria: 'Operational cost',
    comparisonRow2Others: 'High',
    comparisonRow2Greencap: 'Minimal',
    comparisonRow3Criteria: 'Learning curve',
    comparisonRow3Others: 'High',
    comparisonRow3Greencap: 'Low',
    comparisonRow4Criteria: 'Application deploy',
    comparisonRow4Others: 'Multiple manual steps',
    comparisonRow4Greencap: '1 click via Templates',
    comparisonRow5Criteria: 'License',
    comparisonRow5Others: 'Commercial / enterprise',
    comparisonRow5Greencap: 'Open source'
  }
};
