export const translations = {
  'pt-br': {
    featuresEyebrow: 'Funcionalidades',
    featuresTitle: 'Tudo que você precisa para operar clusters no dia a dia',
    featuresGlobalTitle: 'Global — visão de infraestrutura',
    featuresGlobalItem1: 'Múltiplos Clusters e Namespaces',
    featuresGlobalItem2: 'Nodes, PersistentVolumes e StorageClasses',
    featuresGlobalItem3: 'Registry interno de imagens',
    featuresProjectTitle: 'Project — por Namespace',
    featuresProjectItem1: 'Topologia visual interativa',
    featuresProjectItem2: 'Observability: Dashboard, Events, Metrics',
    featuresProjectItem3: 'Workloads: Pods, Deployments, StatefulSets, Jobs, CronJobs',
    featuresProjectItem4: 'Networking, Parameters, Auto Scaling, Storage, Helm',
    featuresDeployTitle: '4 formas de deploy',
    featuresDeployItem1: 'Deploy Application — a partir de imagem',
    featuresDeployItem2: 'Import Compose — traduz docker-compose.yml automaticamente',
    featuresDeployItem3: 'Deploy from Dockerfile — build via Kaniko + deploy em um fluxo',
    featuresDeployItem4: 'Deploy from Helm — wizard guiado',
    featuresDxTitle: 'Developer Experience',
    featuresDxItem1: 'Templates Catalog — apps completas prontas para deploy em 1 clique (ex.: Flask + PostgreSQL, MongoDB cache-aside)',
    featuresDxItem2: 'Kubernetes Operators via OLM — catálogo, instalação e status em tempo real'
  },
  'en': {
    featuresEyebrow: 'Features',
    featuresTitle: 'Everything you need to run clusters day to day',
    featuresGlobalTitle: 'Global — infrastructure view',
    featuresGlobalItem1: 'Multiple Clusters and Namespaces',
    featuresGlobalItem2: 'Nodes, PersistentVolumes and StorageClasses',
    featuresGlobalItem3: 'Internal image registry',
    featuresProjectTitle: 'Project — per Namespace',
    featuresProjectItem1: 'Interactive visual topology',
    featuresProjectItem2: 'Observability: Dashboard, Events, Metrics',
    featuresProjectItem3: 'Workloads: Pods, Deployments, StatefulSets, Jobs, CronJobs',
    featuresProjectItem4: 'Networking, Parameters, Auto Scaling, Storage, Helm',
    featuresDeployTitle: '4 ways to deploy',
    featuresDeployItem1: 'Deploy Application — from an image',
    featuresDeployItem2: 'Import Compose — automatically translates docker-compose.yml',
    featuresDeployItem3: 'Deploy from Dockerfile — build via Kaniko + deploy in one flow',
    featuresDeployItem4: 'Deploy from Helm — guided wizard',
    featuresDxTitle: 'Developer Experience',
    featuresDxItem1: 'Templates Catalog — complete apps ready to deploy in 1 click (e.g. Flask + PostgreSQL, MongoDB cache-aside)',
    featuresDxItem2: 'Kubernetes Operators via OLM — catalog, install and real-time status'
  }
};
